# Generated by Django 4.1.3 on 2022-11-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCode', models.CharField(max_length=10)),
                ('productName', models.CharField(max_length=50)),
                ('productPrice', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCode', models.CharField(max_length=10)),
                ('productName', models.CharField(default='NULL', max_length=50)),
                ('productPrice', models.FloatField(default='NULL', max_length=50)),
                ('totalPayment', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Purchases',
            },
        ),
    ]
