# Generated by Django 4.1.3 on 2022-11-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashRegisterApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='productCode',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='productPrice',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
